"""
chaos_deploy.py — Deploy the Chaos OpenClaw stack to Server 3.

Run as overlord101 during the standard deploy (infra/deploy.py).
Idempotent: safe to re-run after any change to docker-compose.yml,
openclaw.json, or .env values.

Steps (all idempotent):
  1. Ensure /opt/openclaw/chaos/ exists, overlord101:overlord101, mode 0750.
  2. Upload docker-compose.yml.
  3. Upload config/openclaw.json (mode 0640).
  4. Render + upload remote .env (mode 0600) from local os.environ.
  5. docker compose pull + docker compose up -d.
  6. Poll http://127.0.0.1:18789/healthz up to 240s — fail loudly on timeout.
  7. docker compose exec chaos openclaw config validate — fail loudly on
     schema drift.

Required local env vars (read from the laptop's .env via `set -a; source
.env; set +a`). Missing vars raise KeyError and abort the run:
  CHAOS_IMAGE
  CHAOS_GATEWAY_TOKEN
  CHAOS_LITELLM_BASE_URL
  CHAOS_LITELLM_API_KEY

Optional (defaults shown):
  TZ                         (default: "UTC")
  CHAOS_SLACK_BOT_TOKEN      (default: "")
  CHAOS_SLACK_APP_TOKEN      (default: "")
  CHAOS_SLACK_SIGNING_SECRET (default: "")
  CHAOS_SEARXNG_BASE_URL     (default: "")
"""

import os
from io import StringIO

from pyinfra import host
from pyinfra.operations import files, server

# ---------------------------------------------------------------------------
# Config — paths + required/optional env vars
# ---------------------------------------------------------------------------
deploy_user = host.data.deploy_user                         # "overlord101"
chaos_dir = host.data.chaos_dir                             # "/opt/openclaw/chaos"

# Required: fail loudly if missing. Use os.environ[...] (not os.getenv).
REQUIRED_ENV = [
    "CHAOS_IMAGE",
    "CHAOS_GATEWAY_TOKEN",
    "CHAOS_LITELLM_BASE_URL",
    "CHAOS_LITELLM_API_KEY",
]

missing = [k for k in REQUIRED_ENV if not os.environ.get(k)]
if missing:
    raise RuntimeError(
        "chaos_deploy.py — missing required env vars: "
        + ", ".join(missing)
        + ". Populate them in the local .env and re-run."
    )

# Remote-side .env is rendered from these values. Optional ones default to
# empty strings so compose substitution and openclaw.json validation both
# tolerate the scaffolding slots on day one.
env_values = {
    "CHAOS_IMAGE":                os.environ["CHAOS_IMAGE"],
    "TZ":                         os.environ.get("TZ", "UTC"),
    "CHAOS_GATEWAY_TOKEN":        os.environ["CHAOS_GATEWAY_TOKEN"],
    "CHAOS_LITELLM_BASE_URL":     os.environ["CHAOS_LITELLM_BASE_URL"],
    "CHAOS_LITELLM_API_KEY":      os.environ["CHAOS_LITELLM_API_KEY"],
    "CHAOS_SLACK_BOT_TOKEN":      os.environ.get("CHAOS_SLACK_BOT_TOKEN", ""),
    "CHAOS_SLACK_APP_TOKEN":      os.environ.get("CHAOS_SLACK_APP_TOKEN", ""),
    "CHAOS_SLACK_SIGNING_SECRET": os.environ.get("CHAOS_SLACK_SIGNING_SECRET", ""),
    "CHAOS_SEARXNG_BASE_URL":     os.environ.get("CHAOS_SEARXNG_BASE_URL", ""),
}

# Render the remote .env as simple KEY=VALUE lines in a deterministic order.
# Kept in-file (not a Jinja template) to avoid a one-key-per-line template
# in infra/files/chaos/ that would drift from REQUIRED_ENV.
remote_env_lines = [
    "# Generated by infra/tasks/chaos_deploy.py — do not edit by hand.",
    "# Re-run `pyinfra infra/inventories/deploy.py infra/deploy.py` to regenerate.",
    "",
    f"CHAOS_IMAGE={env_values['CHAOS_IMAGE']}",
    f"TZ={env_values['TZ']}",
    "",
    f"CHAOS_GATEWAY_TOKEN={env_values['CHAOS_GATEWAY_TOKEN']}",
    "",
    f"CHAOS_LITELLM_BASE_URL={env_values['CHAOS_LITELLM_BASE_URL']}",
    f"CHAOS_LITELLM_API_KEY={env_values['CHAOS_LITELLM_API_KEY']}",
    "",
    f"CHAOS_SLACK_BOT_TOKEN={env_values['CHAOS_SLACK_BOT_TOKEN']}",
    f"CHAOS_SLACK_APP_TOKEN={env_values['CHAOS_SLACK_APP_TOKEN']}",
    f"CHAOS_SLACK_SIGNING_SECRET={env_values['CHAOS_SLACK_SIGNING_SECRET']}",
    "",
    f"CHAOS_SEARXNG_BASE_URL={env_values['CHAOS_SEARXNG_BASE_URL']}",
    "",
]
remote_env_content = "\n".join(remote_env_lines)

# ---------------------------------------------------------------------------
# 1. Ensure /opt/openclaw/chaos/ exists, owned by overlord101, mode 0750.
#    Also pre-create the state/ and workspace/ subdirs so the compose bind
#    mounts land on overlord101-owned paths (not root-owned, which would
#    cause the non-root container user inside the image to hit EACCES).
# ---------------------------------------------------------------------------
files.directory(
    name=f"Ensure {chaos_dir} exists",
    path=chaos_dir,
    present=True,
    user=deploy_user,
    group=deploy_user,
    mode="750",
)

files.directory(
    name=f"Ensure {chaos_dir}/config exists",
    path=f"{chaos_dir}/config",
    present=True,
    user=deploy_user,
    group=deploy_user,
    mode="750",
)

files.directory(
    name=f"Ensure {chaos_dir}/state exists",
    path=f"{chaos_dir}/state",
    present=True,
    user=deploy_user,
    group=deploy_user,
    mode="750",
)

files.directory(
    name=f"Ensure {chaos_dir}/workspace exists",
    path=f"{chaos_dir}/workspace",
    present=True,
    user=deploy_user,
    group=deploy_user,
    mode="750",
)

# ---------------------------------------------------------------------------
# 2. Upload docker-compose.yml.
# ---------------------------------------------------------------------------
files.put(
    name="Upload chaos docker-compose.yml",
    src="docker/chaos/docker-compose.yml",
    dest=f"{chaos_dir}/docker-compose.yml",
    user=deploy_user,
    group=deploy_user,
    mode="640",
)

# ---------------------------------------------------------------------------
# 3. Upload openclaw.json (baked agent config).
# ---------------------------------------------------------------------------
files.put(
    name="Upload openclaw.json",
    src="docker/chaos/config/openclaw.json",
    dest=f"{chaos_dir}/config/openclaw.json",
    user=deploy_user,
    group=deploy_user,
    mode="640",
)

# ---------------------------------------------------------------------------
# 4. Render + upload remote .env (mode 0600). Values come from os.environ;
#    the file itself is a simple KEY=VALUE dump. docker compose reads this
#    automatically from the same directory as docker-compose.yml.
# ---------------------------------------------------------------------------
files.put(
    name="Upload rendered .env for chaos",
    src=StringIO(remote_env_content),
    dest=f"{chaos_dir}/.env",
    user=deploy_user,
    group=deploy_user,
    mode="600",
)

# ---------------------------------------------------------------------------
# 5. docker compose pull + up -d.
#    overlord101 is in the docker group (see docker_install.py), so these
#    run without sudo. Override the inventory-wide _sudo=True.
# ---------------------------------------------------------------------------
server.shell(
    name="Pull chaos image",
    commands=[f"cd {chaos_dir} && docker compose pull"],
    _sudo=False,
    _timeout=300,
)

server.shell(
    name="Bring chaos stack up (docker compose up -d)",
    commands=[f"cd {chaos_dir} && docker compose up -d"],
    _sudo=False,
    _timeout=180,
)

# ---------------------------------------------------------------------------
# 6. Poll /healthz up to 240s. Emits one dot per poll attempt for log trail.
#    Fails loudly (exit 1) on timeout — Pyinfra aborts the run.
# ---------------------------------------------------------------------------
healthcheck_cmd = (
    "for i in $(seq 1 48); do "
    "  if curl -fsS http://127.0.0.1:18789/healthz >/dev/null 2>&1; then "
    "    echo healthy; exit 0; "
    "  fi; "
    "  sleep 5; "
    "done; "
    "echo 'chaos /healthz never became green after 240s' >&2; "
    "docker logs --tail=100 chaos >&2 || true; "
    "exit 1"
)

server.shell(
    name="Wait for chaos /healthz (up to 240s)",
    commands=[healthcheck_cmd],
    _sudo=False,
    _timeout=300,
)

# ---------------------------------------------------------------------------
# 7. Validate the baked openclaw.json against the in-container schema.
#    Any schema drift fails the run.
# ---------------------------------------------------------------------------
server.shell(
    name="Validate openclaw.json (openclaw config validate)",
    commands=[
        f"cd {chaos_dir} && docker compose exec -T chaos openclaw config validate"
    ],
    _sudo=False,
    _timeout=60,
)
