use_default_settings: true

general:
  instance_name: "chaos-searxng"
  privacypolicy_url: false
  donation_url: false
  contact_url: false

search:
  safe_search: 0
  autocomplete: ""
  formats:
    - html
    - json

server:
  secret_key: "placeholder-overridden-by-env"
  limiter: false
  image_proxy: false
  public_instance: false

ui:
  static_use_hash: true
  default_locale: "en"

redis:
  url: false
